### ISSUE TITLE
Continued improvement of UG and DG

### ISSUE THREAD

**Issue by e0008233** [CS2103AUG2016-T16-C2/main#63]
Be the boss

**Comment by Halo3fanz** [comment]
Improve introduction. NOT ENOUGH @lijen1994 
Step 3 - Change name to TPTM or Task Manager
Show how the commands respond
Take out grey line from number 6
Number 7 should reflect that cheat sheet is now below it
Under `add` task, examples should be listed from simplest to hardest
List doesnt need that grey line
Under `find`, the word "given" should be replaced
The example should reflect that `find` is no longer case sensitive
Under `delete`, the alert should not be bolded and should instead should be in a vertical grey line
Under `select` and `list`, avoid repeating description
In the alert under `clear`, insert commas to punctuate sentence properly
Check for spelling errors and case words properly eg "Computer"

**Comment by lijen1994** [comment]
Converted both UG and DG into docx format for easier transition
Update content to reflect changes 
Corrected spelling and grammar

**Comment by lijen1994** [comment]
Revised UG format on both docx and on git
Still need to add screenshots of finalized UI next week
DG is still being worked on
Waiting review from group members on UG

**Comment by lijen1994** [comment]
Made some more tweeks to UG and DG
Sent UG and DG for comments

**Comment by lijen1994** [comment]
Added in Pictures into CS2101 version, compiled version for CS2103 is 60% complete.
