### ISSUE TITLE
Set up coverage reporting

### ISSUE THREAD

**Issue by damithc** [CS2103AUG2016-T16-C2/main#66]
Congrats on setting up Travis and getting the build to pass. May be you can set up coverage reporting as well so that it shows up in [this page](https://github.com/nus-cs2103/website/blob/master/contents/teams.md)?

**Comment by lijen1994** [comment]
Have done so but experiencing issues with getting Travis to work

**Comment by damithc** [comment]
Looks like 2 tests are failing on travis. Are they passing locally?
Try running tests in headless mode using gradle. The result should be pretty close to what happens on travis.
