### ISSUE TITLE
V0.3 feedback

### ISSUE THREAD

**Issue by PierceAndy** [CS2103AUG2016-T16-C2/main#76]
## User Guide
- Good job adding a screen shot. However, it would greatly help your user understand the layout of your interface if your screenshot had labels and explanations for each component (e.g. Where is the console window where messages to the user are displayed?).
- You might want to use more screenshots to illustrate what happens after entering each command. Additionally, it would be wise to use partial screenshots capturing only the part in concern. Otherwise you'll have to update all screenshots when some minor detail of the GUI changes.
- See if you can make the command format easier to type. Try different symbols and find the one that doesn't slow down the typing speed. Just because DOS uses x/ doesn't mean you are stuck with it. Jim is a Windows user and a fast typist, but that doesn't mean he is used to typing DOS commands. Just don't assume he is used to typing Unix commands because that's a confirmed 'no'.
- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.
- Is it a good idea to tell the user to look at another function's (add's) help section to find out what kinds of inputs are valid for the edit function?
- The ordering of commands could be more meaningful, and it would be easier to follow if it also followed the order as defined in the command summary.
## Developer's Guide
- Some of the text in your component diagrams are too small to view directly in the developer's document, and there's too much negative space.
- Figure 2 is not a class diagram <img width="673" alt="Figure 2" src="https://cloud.githubusercontent.com/assets/8639005/19678078/d3ffd8ca-9ace-11e6-9fd9-6ba4e26f4afc.png">
- All commands in the logic component should have been included in the logic component diagram ![Logic component](https://cloud.githubusercontent.com/assets/8639005/19677437/e9493580-9acb-11e6-9aaf-f45631c621b0.png)
- The model component section is outdated, and refers to the Address Book, and there's a typo for `UnmodifiableObservableList` in the diagram.
- The interfaces in your diagrams should be named as well.
## About Us
- Check that all links point to where they should.

**Comment by lijen1994** [comment]
Will upload the latest revision by Friday.
